import { useEffect, useState } from "react";
import { AlertTriangle, Info, RefreshCw, Server, SlidersHorizontal } from "lucide-react";
import { Badge, Card, ErrorBlock, LoadingBlock, ProgressBar, Spinner } from "../components/ui";
import { api } from "../services/api";
import { useApi } from "../hooks/useApi";
import { formatDate } from "../utils/format";
import type { TrainingStatus } from "../types";

const DISCLAIMER =
  "Predictions are estimates generated by a statistical model and may differ materially from actual box-office results. Use the forecast range, not the point estimate, as your planning reference. Model confidence reflects training accuracy and feature completeness, not a probability of success.";

export function SettingsPage() {
  const info = useApi(() => api.modelInfo(), []);
  const [retraining, setRetraining] = useState(false);
  const [status, setStatus] = useState<TrainingStatus | null>(null);
  const [actionMsg, setActionMsg] = useState<string | null>(null);

  const pollStatus = async () => {
    try {
      const s = await api.trainingStatus();
      setStatus(s);
      setRetraining(s.status === "running");
      return s;
    } catch {
      return null;
    }
  };

  useEffect(() => {
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout> | undefined;

    const tick = async () => {
      const s = await pollStatus();
      if (cancelled) return;
      if (s && s.status === "running") {
        timer = setTimeout(tick, 3000);
      }
    };

    pollStatus().then(() => {
      if (!cancelled && status?.status === "running") {
        timer = setTimeout(tick, 3000);
      }
    });
    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const triggerRetrain = async () => {
    setActionMsg(null);
    try {
      const s = await api.retrain();
      setStatus(s);
      if (s.status === "started" || s.status === "already_running") {
        setRetraining(true);
        // start polling
        const loop = async () => {
          const next = await pollStatus();
          if (next && next.status === "running") setTimeout(loop, 3000);
        };
        setTimeout(loop, 500);
      }
    } catch (e) {
      setActionMsg((e as { message: string }).message);
      setRetraining(false);
    }
  };

  if (info.loading) return <LoadingBlock label="Loading settings…" />;
  if (info.error) return <ErrorBlock code={info.error.code} message={info.error.message} onRetry={info.refetch} />;

  const thresholds = Object.entries(info.data?.performance_thresholds ?? {});
  const maxRatio = thresholds.length ? Math.max(...thresholds.map(([, r]) => r)) : 1;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-extrabold tracking-tight text-zinc-100">
          Settings & <span className="gradient-text">Model Management</span>
        </h1>
        <p className="mt-1 text-sm text-zinc-400">Inspect the model, retrain it, and understand the thresholds</p>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <Card>
          <div className="mb-4 flex items-center gap-2">
            <Server className="h-4 w-4 text-violet-400" />
            <h2 className="section-title">Model Registry</h2>
          </div>
          <div className="space-y-3">
            {[
              { l: "Version", v: `v${info.data?.model_version}` },
              { l: "Type", v: info.data?.model_type },
              { l: "Framework", v: info.data?.framework },
              { l: "Target variable", v: info.data?.target_variable },
              { l: "Feature count", v: `${info.data?.feature_count}` },
              { l: "Training date", v: formatDate(info.data?.training_date) },
              { l: "Training duration", v: info.data?.training_duration_seconds != null ? `${info.data.training_duration_seconds.toFixed(1)}s` : "—" },
            ].map((s) => (
              <div key={s.l} className="flex items-center justify-between border-b border-white/5 pb-2.5">
                <span className="text-sm text-zinc-400">{s.l}</span>
                <span className="text-sm font-semibold text-zinc-100">{s.v}</span>
              </div>
            ))}
          </div>
        </Card>

        <Card>
          <div className="mb-4 flex items-center gap-2">
            <SlidersHorizontal className="h-4 w-4 text-cyan-400" />
            <h2 className="section-title">Performance Thresholds</h2>
          </div>
          <p className="section-sub mb-4">Revenue-to-budget multiplier used to label a prediction</p>
          <div className="space-y-2.5">
            {thresholds.map(([label, ratio]) => (
              <div key={label} className="flex items-center gap-3">
                <span className="w-28 shrink-0 text-sm font-semibold text-zinc-200">
                  {label.replace("_", " ")}
                </span>
                <div className="flex-1">
                  <ProgressBar value={(ratio / maxRatio) * 100} tone={label === "BLOCKBUSTER" ? "emerald" : "violet"} />
                </div>
                <span className="w-16 shrink-0 text-right font-mono text-sm text-zinc-300">
                  {ratio >= 1e9 ? "8.0x+" : `${ratio.toFixed(1)}x`}
                </span>
              </div>
            ))}
          </div>
          <div className="mt-4 rounded-xl bg-white/[0.03] p-3 text-xs text-zinc-500">
            ratio = predicted revenue ÷ budget. A movie with ratio ≥ 8.0 is labelled BLOCKBUSTER.
          </div>
        </Card>
      </div>

      <Card>
        <div className="mb-4 flex items-center gap-2">
          <RefreshCw className="h-4 w-4 text-emerald-400" />
          <h2 className="section-title">Retraining</h2>
        </div>
        <p className="section-sub mb-4">
          Re-runs the full training pipeline on the processed TMDB 5000 dataset and replaces the active model.
        </p>

        <div className="flex flex-wrap items-center gap-4">
          <button className="btn-primary" onClick={triggerRetrain} disabled={retraining}>
            {retraining ? <Spinner size={18} /> : <RefreshCw className="h-4 w-4" />}
            {retraining ? "Training in progress…" : "Retrain Model"}
          </button>
          {status && status.status === "running" && (
            <div className="flex items-center gap-3 text-sm text-zinc-300">
              <Spinner size={18} />
              Epoch {status.current_epoch ?? "—"} / {status.total_epochs ?? "?"}
            </div>
          )}
          {status && status.status === "completed" && (
            <Badge className="border-emerald-400/40 bg-emerald-400/10 text-emerald-300">
              ✓ Training completed {formatDate(status.completed_at)}
            </Badge>
          )}
          {status && status.status === "failed" && (
            <Badge className="border-rose-400/40 bg-rose-400/10 text-rose-300">
              ✗ Failed: {status.message}
            </Badge>
          )}
        </div>

        {actionMsg && (
          <div className="mt-4 flex items-center gap-2 rounded-xl bg-rose-500/10 px-3 py-2.5 text-sm text-rose-300">
            <AlertTriangle className="h-4 w-4" /> {actionMsg}
          </div>
        )}
        {status && status.status === "running" && (
          <div className="mt-4 rounded-xl bg-cyan-500/10 px-3 py-2.5 text-xs text-cyan-200">
            {status.message}
          </div>
        )}
      </Card>

      <Card>
        <div className="flex items-start gap-3">
          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-violet-500/15">
            <Info className="h-4 w-4 text-violet-300" />
          </div>
          <div>
            <h2 className="section-title">Important Disclaimer</h2>
            <p className="mt-1 max-w-3xl text-sm leading-relaxed text-zinc-400">{DISCLAIMER}</p>
          </div>
        </div>
      </Card>
    </div>
  );
}
